defmodule Nest.Persistence do
  @moduledoc """
  Wrapper around the DB-touching parts of starting an Agent
  and the agent + message persistence layer.

  Centralises the "load and start" pattern so test code and
  production code call the same function. Tests rely on the
  test process already owning a sandboxed connection (see
  `Nest.DataCase.setup_sandbox/1`); production uses the global
  Ecto pool. Either way, the DB read happens in the calling
  process, which lets the Agent's `init/1` skip DB work and
  inherit `$callers` for subsequent handler DB writes.

  ## Why this exists

  The Agent's `init/1` historically called
  `Vocations.get_vocation/1` itself. That worked in sync tests
  but broke async tests: the Ecto Sandbox's `shared: true` mode
  is repo-wide, so concurrent async tests racing for it got
  `:already_shared`. Moving the load to the calling process
  sidesteps the shared-mode lock entirely — the caller already
  has a connection via the regular pool (or the test's
  sandboxed checkout), and the agent's later `Repo` calls walk
  `$callers` back to that same connection with no per-pid
  `Sandbox.allow/3`.

  ## Agent + message persistence

  `insert_agent/1` writes a new `agents` row (the integer `id`
  is autogenerated; the `name` is the human identifier).
  `fetch_agent_by_name/1` and `list_agent_names/0` are the
  read paths. The Agent's `__append_message__/2` calls
  `insert_message/2` immediately after appending to in-memory
  state; on `__archive_and_compact__/2` it calls
  `archive_and_compact/4`. `load_active_messages/1` is used by
  the on-demand-load path in `Supervisor.fetch_or_start_agent/1`.

  Externally, callers pass `name` (a String). Internally,
  `messages.agent_id` is the bigserial `agents.id` (an
  integer); this module handles the resolution.

  ## Why retried inserts

  `insert_agent/1` returns `{:error, :duplicate_name}` on a
  Postgres `23505` unique violation. The supervisor catches
  that result, regenerates a fresh name, and retries; the
  unique-index constraint on `agents.name` is the ultimate
  arbiter of uniqueness across BEAMs (two workers picking the
  same adjective-animal combination is rare with the
  in-process `MapSet`, but not impossible).
  """

  import Ecto.Query, warn: false
  require Logger

  alias Ecto.Changeset
  alias Nest.Agents.PersistedAgent
  alias Nest.Agents.PersistedMessage
  alias Nest.Messages.Message
  alias Nest.Repo
  alias Nest.Vocations

  @doc """
  Resolve a `vocation_id` to a loaded `Vocations.Vocation`
  struct (or `nil` if the id is `nil`).

  Returns `nil` (not raising) when the id is non-nil but no
  record exists; matches `Vocations.get_vocation/1`.
  """
  @spec load_vocation(integer() | nil) :: Vocations.Vocation.t() | nil
  def load_vocation(nil), do: nil
  def load_vocation(vocation_id), do: Vocations.get_vocation(vocation_id)

  @doc """
  Build the attrs map the Agent expects, with `:vocation`
  pre-loaded from the DB.

  Pass any other Agent attrs in `attrs` (`name`, `model`,
  `workspace_path`, etc.) — they're merged on top of the
  loaded vocation. `:vocation_id` may be passed by callers
  who don't have the struct handy; this function does the
  fetch and returns the merged map.

  ## Example

      attrs =
        Nest.Persistence.build_agent_attrs(%{
          name: "agent-1",
          model: %{name: "qwen3.5-plus", provider: "model-studio"},
          vocation_id: 42
        })

      Agent.start_link(attrs)
  """
  @spec build_agent_attrs(map()) :: map()
  def build_agent_attrs(attrs) do
    attrs
    |> maybe_load_vocation()
  end

  defp maybe_load_vocation(%{vocation: _vocation} = attrs), do: attrs

  defp maybe_load_vocation(%{vocation_id: id} = attrs) when not is_nil(id) do
    Map.put(attrs, :vocation, load_vocation(id))
  end

  defp maybe_load_vocation(attrs), do: attrs

  @doc """
  Convenience: load the vocation (if any) and start the Agent
  in one call. The caller is responsible for the resulting
  pid (e.g. registering it, supervising it).

  The DB read happens in the calling process; the Agent's
  `init/1` has no DB work. Returns `{:ok, pid}` on success
  (matching `Agent.start_link/1`), or `{:error, reason}` on
  init failure.
  """
  @spec start_agent(map()) :: GenServer.on_start()
  def start_agent(attrs) do
    Agent.start_link(build_agent_attrs(attrs))
  end

  @doc """
  Insert a new agent row. The integer `id` is autogenerated
  by the DB; the human-readable `name` is the identifier the
  Supervisor sends through. `attrs` carries `:name`, `:model`,
  `:vocation_id`, `:workspace_path`. `:next_message_index`
  defaults to 0 and the runtime bumps it via
  `update_next_message_index/2` when messages are appended.

  Returns `{:ok, %PersistedAgent{}}` on success,
  `{:error, :duplicate_name}` when the `agents.name`
  unique index rejects the insert (Postgres `23505`),
  `{:error, :missing_required_field}` when a required
  attribute (`:name`, `:model`) is absent, or
  `{:error, %Ecto.Changeset{}}` on validation failure.
  """
  @spec insert_agent(map()) ::
          {:ok, PersistedAgent.t()}
          | {:error, :duplicate_name | :missing_required_field | Changeset.t(PersistedAgent.t())}
  def insert_agent(attrs) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    case build_insert_base(attrs, now) do
      {:error, _} = err ->
        err

      base ->
        do_insert(base)
    end
  end

  # The base map carries every required field with a default
  # for the optional columns. Returns `{:error, :missing_required_field}`
  # when `:name` or `:model` is missing — the supervisor's
  # `do_fetch_or_start_with_persistence/1` relies on this sentinel
  # to translate the failure into `:not_found` for callers that
  # only had a name (the `get_agent/1` on-demand-load path).
  defp build_insert_base(attrs, now) do
    name = Map.get(attrs, :name)
    model = Map.get(attrs, :model)

    if is_binary(name) and not is_nil(model) do
      %{
        name: name,
        model: model,
        vocation_id: Map.get(attrs, :vocation_id),
        workspace_path: Map.get(attrs, :workspace_path),
        next_message_index: Map.get(attrs, :next_message_index, 0),
        inserted_at: now,
        updated_at: now
      }
    else
      {:error, :missing_required_field}
    end
  end

  # Translate a Postgres `23505` unique violation on `name` into
  # the supervisor-friendly `:duplicate_name` sentinel. Validation
  # errors fall through as the raw `Ecto.Changeset` so callers
  # can render field-level messages.
  defp do_insert(base) do
    case Repo.insert(%PersistedAgent{} |> PersistedAgent.changeset(base)) do
      {:ok, row} ->
        {:ok, row}

      {:error, %Changeset{errors: errors} = changeset} ->
        if duplicate_name?(errors) do
          {:error, :duplicate_name}
        else
          {:error, changeset}
        end
    end
  end

  # The unique constraint on `agents.name` reports as
  # `{:constraint, :unique}` on the Ecto Changeset
  # `errors` list.
  defp duplicate_name?([{:name, {_, [constraint: :unique, constraint_name: _]}} | _]), do: true
  defp duplicate_name?([_ | rest]), do: duplicate_name?(rest)
  defp duplicate_name?([]), do: false

  @doc """
  Fetch the agent row by `name` (the human identifier).
  Returns `{:ok, %PersistedAgent{}}` when found, otherwise
  `{:error, :not_found}`. Used by the supervisor's restore
  path and by all message-write helpers that resolve the
  FK from a name.
  """
  @spec fetch_agent_by_name(String.t()) ::
          {:ok, PersistedAgent.t()} | {:error, :not_found}
  def fetch_agent_by_name(name) do
    case from(a in PersistedAgent, where: a.name == ^name) |> Repo.one() do
      nil -> {:error, :not_found}
      %PersistedAgent{} = row -> {:ok, row}
    end
  end

  @doc """
  List every agent name currently persisted. Used by the
  `Supervisor`'s name generator to pre-load existing
  names into the in-process uniqueness `MapSet`, reducing
  the probability of a Postgres unique-constraint collision.
  """
  @spec list_agent_names() :: [String.t()]
  def list_agent_names do
    from(a in PersistedAgent, select: a.name)
    |> Repo.all()
  end

  @doc """
  Persist a runtime message into the `messages` table.

  `agent_name` is the owning agent's human identifier.
  `message` is the canonical `Message.t()` tagged tuple
  (`:system`, `:user`, `:assistant`, `:tool`, `:compaction`).
  The agent's integer FK (`agents.id`) is resolved
  internally.

  Returns `{:ok, %PersistedMessage{}}` on success, or
  `{:error, term()}` on failure (including
  `{:error, :agent_not_found}` when the agent name does
  not resolve to a row).
  """
  @spec insert_message(String.t(), Message.t()) ::
          {:ok, PersistedMessage.t()} | {:error, term()}
  def insert_message(agent_name, message) do
    case fetch_agent_by_name(agent_name) do
      {:error, :not_found} ->
        {:error, :agent_not_found}

      {:ok, %PersistedAgent{id: agent_id}} ->
        attrs = PersistedMessage.from_runtime(agent_id, message)

        %PersistedMessage{}
        |> PersistedMessage.changeset(attrs)
        |> Repo.insert(
          on_conflict: :nothing,
          conflict_target: [:agent_id, :message_index]
        )
    end
  end

  @doc """
  Mark the messages in `[first_index..last_index]` as
  archived, then insert the compaction marker at
  `last_index + 1`, all in one transaction.

  The caller is `Agent.__archive_and_compact__/2`; it
  computes `first_index` and `last_index` from the agent's
  in-memory `state.chat_state.messages` and the
  compactor-produced `new_messages`. The marker is
  rendered as a `role: "compaction"` row with
  `compaction_archived_count` and `compaction_occurred_at`
  populated.

  Returns the new compaction row on success, or
  `{:error, term()}` on failure (including
  `{:error, :agent_not_found}` when the agent name does
  not resolve to a row).
  """
  @spec archive_and_compact(String.t(), non_neg_integer(), non_neg_integer(), non_neg_integer()) ::
          {:ok, PersistedMessage.t()} | {:error, term()}
  def archive_and_compact(agent_name, first_index, last_index, archived_count) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{id: agent_id}} ->
        now = DateTime.utc_now() |> DateTime.truncate(:second)
        marker_index = last_index + 1

        Repo.transaction(fn ->
          from(m in PersistedMessage,
            where:
              m.agent_id == ^agent_id and m.message_index >= ^first_index and
                m.message_index <= ^last_index
          )
          |> Repo.update_all(set: [archived_at: now])

          %PersistedMessage{}
          |> PersistedMessage.changeset(%{
            agent_id: agent_id,
            message_index: marker_index,
            role: "compaction",
            content: %{"parts" => []},
            inserted_at: now,
            compaction_archived_count: archived_count,
            compaction_occurred_at: now
          })
          |> Repo.insert()
        end)
        |> case do
          {:ok, {:ok, row}} -> {:ok, row}
          {:ok, {:error, reason}} -> {:error, reason}
          {:error, reason} -> {:error, reason}
        end

      {:error, :not_found} ->
        {:error, :agent_not_found}
    end
  end

  @doc """
  Bump the `next_message_index` column on the agent row.

  Called after every successful `insert_message/2` so a
  restarted agent reads the right counter on the next
  message append. One UPDATE per message; a single agent's
  counter is in a single row, so this is O(1) and not a
  contention hot spot.
  """
  @spec update_next_message_index(String.t(), non_neg_integer()) ::
          :ok | {:error, term()}
  def update_next_message_index(agent_name, new_index) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{id: agent_id}} ->
        from(a in PersistedAgent, where: a.id == ^agent_id)
        |> Repo.update_all(
          set: [
            next_message_index: new_index,
            updated_at: DateTime.utc_now() |> DateTime.truncate(:second)
          ]
        )

        :ok

      {:error, :not_found} ->
        {:error, :agent_not_found}
    end
  end

  @doc """
  Load the active (non-archived) messages for an agent, in
  `message_index` order. Returns a list of `Message.t()`
  tagged tuples (the canonical runtime shape).

  Used by the on-demand-load path in
  `Supervisor.fetch_or_start_agent/1`. The caller is
  responsible for converting the list into the agent's
  `state.chat_state.messages` and stamping the
  `next_message_index` from the agent row.
  """
  @spec load_active_messages(String.t()) :: [Message.t()]
  def load_active_messages(agent_name) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{id: agent_id}} ->
        from(m in PersistedMessage,
          where: m.agent_id == ^agent_id and is_nil(m.archived_at),
          order_by: [asc: m.message_index]
        )
        |> Repo.all()
        |> Enum.map(&PersistedMessage.to_runtime/1)

      {:error, :not_found} ->
        []
    end
  end

  @doc """
  Convenience: load the agent row, the active messages, and
  the vocation struct (if any). Returns `{:ok, attrs_map}`
  suitable for passing to `Agent.start_link/1`, or
  `{:error, :not_found}` when no row exists for the name.

  `attrs_map` mirrors `build_agent_attrs/1`'s output: it
  carries the loaded `Vocation` struct on `:vocation`, the
  `model` from the row, the `workspace_path` from the row,
  the `next_message_index` from the row, and a
  `:preloaded_messages` list of `Message.t()` tuples the
  Agent's `init/1` should seed into
  `state.chat_state.messages`.

  Used by `Supervisor.fetch_or_start_agent/1`'s
  on-demand-load path.
  """
  @spec build_attrs_for_start(String.t()) ::
          {:ok, map()} | {:error, :not_found}
  def build_attrs_for_start(agent_name) do
    case fetch_agent_by_name(agent_name) do
      {:error, :not_found} ->
        {:error, :not_found}

      {:ok, %PersistedAgent{} = row} ->
        attrs = %{
          name: row.name,
          model: row.model,
          vocation_id: row.vocation_id,
          workspace_path: row.workspace_path,
          next_message_index: row.next_message_index,
          preloaded_messages: load_active_messages(agent_name),
          vocation: load_vocation(row.vocation_id)
        }

        {:ok, attrs}
    end
  end
end
