defmodule Nest.Persistence do
  @moduledoc """
  Wrapper around the DB-touching parts of starting an Agent
  and the agent + message persistence layer.

  Centralises the "load and start" pattern so test code and
  production code call the same function. Tests rely on the
  test process already owning a sandboxed connection (see
  `Nest.DataCase.setup_sandbox/1`); production uses the global
  Ecto pool. Either way, the DB read happens in the calling
  process, which lets the Agent's `init/1` skip DB work and
  inherit `$callers` for subsequent handler DB writes.

  ## Why this exists

  The Agent's `init/1` historically called
  `Vocations.get_vocation/1` itself. That worked in sync tests
  but broke async tests: the Ecto Sandbox's `shared: true` mode
  is repo-wide, so concurrent async tests racing for it got
  `:already_shared`. Moving the load to the calling process
  sidesteps the shared-mode lock entirely — the caller already
  has a connection via the regular pool (or the test's
  sandboxed checkout), and the agent's later `Repo` calls walk
  `$callers` back to that same connection with no per-pid
  `Sandbox.allow/3`.

  ## Agent + message persistence

  `insert_agent/1` writes a new `agents` row (the integer `id`
  is autogenerated; the `name` is the human identifier).
  `fetch_agent_by_name/1` and `list_agent_names/0` are the
  read paths. The Agent's `__append_message__/2` calls
  `insert_message/2` immediately after appending to in-memory
  state; on `__compaction_completed__/2` it calls
  `record_compaction/3`. `load_messages/1` returns the full
  ordered sequence for the on-demand-load path in
  `Supervisor.fetch_or_start_agent/1`; the caller partitions
  into active/history using `agents.last_compaction_index`
  (read via `last_compaction_index/1` or returned with
  `build_attrs_for_start/1`'s preloaded attrs).

  Externally, callers pass `name` (a String). Internally,
  `messages.agent_id` is the bigserial `agents.id` (an
  integer); this module handles the resolution.

  ## Why retried inserts

  `insert_agent/1` returns `{:error, :duplicate_name}` on a
  Postgres `23505` unique violation. The supervisor catches
  that result, regenerates a fresh name, and retries; the
  unique-index constraint on `agents.name` is the ultimate
  arbiter of uniqueness across BEAMs (two workers picking the
  same adjective-animal combination is rare with the
  in-process `MapSet`, but not impossible).
  """

  import Ecto.Query, warn: false
  require Logger

  alias Ecto.Changeset
  alias Nest.Agents.Agent.Restore
  alias Nest.Agents.PersistedAgent
  alias Nest.Agents.PersistedMessage
  alias Nest.Messages.Message
  alias Nest.Persistence.CompactionMarker
  alias Nest.Repo
  alias Nest.Vocations

  @doc """
  Resolve a `vocation_id` to a loaded `Vocations.Vocation`
  struct (or `nil` if the id is `nil`).

  Returns `nil` (not raising) when the id is non-nil but no
  record exists; matches `Vocations.get_vocation/1`.
  """
  @spec load_vocation(integer() | nil) :: Vocations.Vocation.t() | nil
  def load_vocation(nil), do: nil
  def load_vocation(vocation_id), do: Vocations.get_vocation(vocation_id)

  @doc """
  Build the attrs map the Agent expects, with `:vocation`
  pre-loaded from the DB.

  Pass any other Agent attrs in `attrs` (`name`, `model`,
  `workspace_path`, etc.) — they're merged on top of the
  loaded vocation. `:vocation_id` may be passed by callers
  who don't have the struct handy; this function does the
  fetch and returns the merged map.

  ## Example

      attrs =
        Nest.Persistence.build_agent_attrs(%{
          name: "agent-1",
          model: %{name: "qwen3.5-plus", provider: "model-studio"},
          vocation_id: 42
        })

      Agent.start_link(attrs)
  """
  @spec build_agent_attrs(map()) :: map()
  def build_agent_attrs(attrs) do
    attrs
    |> maybe_load_vocation()
  end

  defp maybe_load_vocation(%{vocation: _vocation} = attrs), do: attrs

  defp maybe_load_vocation(%{vocation_id: id} = attrs) when not is_nil(id) do
    Map.put(attrs, :vocation, load_vocation(id))
  end

  defp maybe_load_vocation(attrs), do: attrs

  @doc """
  Convenience: load the vocation (if any) and start the Agent
  in one call. The caller is responsible for the resulting
  pid (e.g. registering it, supervising it).

  The DB read happens in the calling process; the Agent's
  `init/1` has no DB work. Returns `{:ok, pid}` on success
  (matching `Agent.start_link/1`), or `{:error, reason}` on
  init failure.
  """
  @spec start_agent(map()) :: GenServer.on_start()
  def start_agent(attrs) do
    Agent.start_link(build_agent_attrs(attrs))
  end

  @doc """
  Insert a new agent row. The integer `id` is autogenerated
  by the DB; the human-readable `name` is the identifier the
  Supervisor sends through. `attrs` carries `:name`, `:model`,
  `:vocation_id`, `:workspace_path`. `:next_message_index`
  defaults to 0 and the runtime bumps it via
  `update_next_message_index/2` when messages are appended.

  Returns `{:ok, %PersistedAgent{}}` on success,
  `{:error, :duplicate_name}` when the `agents.name`
  unique index rejects the insert (Postgres `23505`),
  `{:error, :missing_required_field}` when a required
  attribute (`:name`, `:model`) is absent, or
  `{:error, %Ecto.Changeset{}}` on validation failure.
  """
  @spec insert_agent(map()) ::
          {:ok, PersistedAgent.t()}
          | {:error, :duplicate_name | :missing_required_field | Changeset.t(PersistedAgent.t())}
  def insert_agent(attrs) do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    case build_insert_base(attrs, now) do
      {:error, _} = err ->
        err

      base ->
        do_insert(base)
    end
  end

  # The base map carries every required field with a default
  # for the optional columns. Returns `{:error, :missing_required_field}`
  # when `:name` or `:model` is missing — the supervisor's
  # `do_fetch_or_start_with_persistence/1` relies on this sentinel
  # to translate the failure into `:not_found` for callers that
  # only had a name (the `get_agent/1` on-demand-load path).
  defp build_insert_base(attrs, now) do
    name = Map.get(attrs, :name)
    model = Map.get(attrs, :model)

    if is_binary(name) and not is_nil(model) do
      %{
        name: name,
        model: model,
        vocation_id: Map.get(attrs, :vocation_id),
        workspace_path: Map.get(attrs, :workspace_path),
        next_message_index: Map.get(attrs, :next_message_index, 0),
        inserted_at: now,
        updated_at: now
      }
    else
      {:error, :missing_required_field}
    end
  end

  # Translate a Postgres `23505` unique violation on `name` into
  # the supervisor-friendly `:duplicate_name` sentinel. Validation
  # errors fall through as the raw `Ecto.Changeset` so callers
  # can render field-level messages.
  defp do_insert(base) do
    case Repo.insert(%PersistedAgent{} |> PersistedAgent.changeset(base)) do
      {:ok, row} ->
        {:ok, row}

      {:error, %Changeset{errors: errors} = changeset} ->
        if duplicate_name?(errors) do
          {:error, :duplicate_name}
        else
          {:error, changeset}
        end
    end
  end

  # The unique constraint on `agents.name` reports as
  # `{:constraint, :unique}` on the Ecto Changeset
  # `errors` list.
  defp duplicate_name?([{:name, {_, [constraint: :unique, constraint_name: _]}} | _]), do: true
  defp duplicate_name?([_ | rest]), do: duplicate_name?(rest)
  defp duplicate_name?([]), do: false

  @doc """
  Fetch the agent row by `name` (the human identifier).
  Returns `{:ok, %PersistedAgent{}}` when found, otherwise
  `{:error, :not_found}`. Used by the supervisor's restore
  path and by all message-write helpers that resolve the
  FK from a name.
  """
  @spec fetch_agent_by_name(String.t()) ::
          {:ok, PersistedAgent.t()} | {:error, :not_found}
  def fetch_agent_by_name(name) do
    case from(a in PersistedAgent, where: a.name == ^name) |> Repo.one() do
      nil -> {:error, :not_found}
      %PersistedAgent{} = row -> {:ok, row}
    end
  end

  @doc """
  List every agent name currently persisted. Used by the
  `Supervisor`'s name generator to pre-load existing
  names into the in-process uniqueness `MapSet`, reducing
  the probability of a Postgres unique-constraint collision.
  """
  @spec list_agent_names() :: [String.t()]
  def list_agent_names do
    from(a in PersistedAgent, select: a.name)
    |> Repo.all()
  end

  @doc """
  Persist a runtime message into the `messages` table.

  `agent_name` is the owning agent's human identifier.
  `message` is the canonical `Message.t()` tagged tuple
  (`:system`, `:user`, `:assistant`, `:tool`, `:compaction`).
  The agent's integer FK (`agents.id`) is resolved
  internally.

  Returns `{:ok, %PersistedMessage{}}` on success, or
  `{:error, term()}` on failure (including
  `{:error, :agent_not_found}` when the agent name does
  not resolve to a row).
  """
  @spec insert_message(String.t(), Message.t()) ::
          {:ok, PersistedMessage.t()} | {:error, term()}
  def insert_message(agent_name, message) do
    case fetch_agent_by_name(agent_name) do
      {:error, :not_found} ->
        {:error, :agent_not_found}

      {:ok, %PersistedAgent{id: agent_id}} ->
        attrs = PersistedMessage.from_runtime(agent_id, message)

        %PersistedMessage{}
        |> PersistedMessage.changeset(attrs)
        |> Repo.insert(
          on_conflict: :nothing,
          conflict_target: [:agent_id, :message_index]
        )
    end
  end

  @doc """
  Insert a `role: "compaction"` marker row at `marker_index`
  and bump `agents.last_compaction_index` to match. Both
  writes happen inside one `Repo.transaction` so the marker
  row and the boundary pointer commit together — a partial
  commit would produce a wrong partition on the next restore
  (rows that should be `messages` would land in `history` or
  vice versa).

  The `messages` table receives the marker INSERT only —
  the prior `archive_and_compact/4` UPDATE on
  `messages.archived_at` is gone, along with the
  `messages.archived_at` column itself. The `messages` table
  is now append-only for its own rows.

  `archived_count` is recorded on the marker
  (`compaction_archived_count`) so `CompactionLifecycle.apply/2`
  can walk backwards through history slices for the
  `compute_first_index/2` step.

  `tokens_compacted` and `tokens_compacted_to` are the
  pre/post totals computed by the caller at compaction time
  (via `Nest.Tokens.Estimator.estimate_messages/1`). Either
  may be nil for legacy callers or for compactor paths that
  don't have both numbers available — the columns are
  nullable so the marker row still inserts.

  Implementation lives in `Nest.Persistence.CompactionMarker`;
  this is a thin delegator that resolves the agent row then
  forwards the integer `agent_id`.

  Returns the new marker row on success,
  `{:error, :agent_not_found}` when the agent name does not
  resolve, or `{:error, term()}` on other failures.
  """
  @spec record_compaction(
          String.t(),
          non_neg_integer(),
          non_neg_integer(),
          non_neg_integer() | nil,
          non_neg_integer() | nil
        ) :: {:ok, PersistedMessage.t()} | {:error, term()}
  def record_compaction(
        agent_name,
        marker_index,
        archived_count,
        tokens_compacted \\ nil,
        tokens_compacted_to \\ nil
      ) do
    with {:ok, %PersistedAgent{id: agent_id}} <- fetch_agent_by_name(agent_name) do
      CompactionMarker.record(
        agent_id,
        marker_index,
        archived_count,
        tokens_compacted,
        tokens_compacted_to
      )
    end
  end

  @doc """
  Bump the `next_message_index` column on the agent row.

  Called after every successful `insert_message/2` so a
  restarted agent reads the right counter on the next
  message append. One UPDATE per message; a single agent's
  counter is in a single row, so this is O(1) and not a
  contention hot spot.
  """
  @spec update_next_message_index(String.t(), non_neg_integer()) ::
          :ok | {:error, term()}
  def update_next_message_index(agent_name, new_index) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{id: agent_id}} ->
        from(a in PersistedAgent, where: a.id == ^agent_id)
        |> Repo.update_all(
          set: [
            next_message_index: new_index,
            updated_at: DateTime.utc_now() |> DateTime.truncate(:second)
          ]
        )

        :ok

      {:error, :not_found} ->
        {:error, :agent_not_found}
    end
  end

  @doc """
  Load every message for an agent (active + history + compaction
  markers), in `message_index` order. Returns a list of
  `Message.t()` tagged tuples — the canonical runtime shape.

  This is the single consistent sequence restored by the
  on-demand-load path in `Supervisor.fetch_or_start_agent/1`.
  The caller partitions the list into
  `state.chat_state.history` (rows with
  `message_index <= agents.last_compaction_index`) and
  `state.chat_state.messages` (rows strictly greater).
  Compaction markers live in `state.chat_state.history` by that
  same rule — they sit at the boundary, not in the active slice.

  The previous `load_active_messages/1` filter
  (`is_nil(archived_at) AND role != "compaction"`) is gone:
  active/history is a view computed from
  `agents.last_compaction_index`, not a filter on the rows
  themselves.
  """
  @spec load_messages(String.t()) :: [Message.t()]
  def load_messages(agent_name) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{id: agent_id}} ->
        from(m in PersistedMessage,
          where: m.agent_id == ^agent_id,
          order_by: [asc: m.message_index]
        )
        |> Repo.all()
        |> Enum.map(&PersistedMessage.to_runtime/1)

      {:error, :not_found} ->
        []
    end
  end

  @doc """
  Read the `last_compaction_index` boundary column from the
  agents row. Returns `{:ok, -1}` for fresh agents (no compaction
  has happened) and the marker's `message_index` (an integer
  `>= 0`) after the first compaction. Returns
  `{:error, :agent_not_found}` when the name does not resolve.

  Used by the on-demand-load path in
  `Supervisor.fetch_or_start_agent/1` (returned via
  `build_attrs_for_start/1`) and by callers that need the
  boundary without doing a full message load.
  """
  @spec last_compaction_index(String.t()) ::
          {:ok, integer()} | {:error, :agent_not_found}
  def last_compaction_index(agent_name) do
    case fetch_agent_by_name(agent_name) do
      {:ok, %PersistedAgent{last_compaction_index: idx}} -> {:ok, idx}
      {:error, :not_found} -> {:error, :agent_not_found}
    end
  end

  @doc """
  Convenience: load the agent row, the full message sequence,
  the boundary pointer, and the vocation struct. Returns
  `{:ok, attrs_map}` suitable for passing to
  `Agent.start_link/1`, or `{:error, :not_found}` when no row
  exists for the name.

  `attrs_map` carries the loaded `Vocation` struct on
  `:vocation`, the `model` from the row, the `workspace_path`
  from the row, the `next_message_index` from the row, the
  `:last_compaction_index` boundary, the
  `:initial_api_log_sequences` map to seed
  `state.chat_state.api_log_sequences` (computed via
  `Restore.initial_sequences_for/1`), and a `:preloaded_messages`
  list of every `Message.t()` the Agent's `init/1` should split
  into `state.chat_state.messages` and `state.chat_state.history`.

  Used by `Supervisor.fetch_or_start_agent/1`'s on-demand-load
  path.
  """
  @spec build_attrs_for_start(String.t()) ::
          {:ok, map()} | {:error, :not_found}
  def build_attrs_for_start(agent_name) do
    with {:ok, row} <- fetch_agent_by_name(agent_name),
         {:ok, boundary} <- last_compaction_index(agent_name) do
      preloaded = load_messages(agent_name)

      attrs = %{
        name: row.name,
        model: row.model,
        vocation_id: row.vocation_id,
        workspace_path: row.workspace_path,
        next_message_index: row.next_message_index,
        last_compaction_index: boundary,
        initial_api_log_sequences: Restore.initial_sequences_for(preloaded),
        preloaded_messages: preloaded,
        vocation: load_vocation(row.vocation_id)
      }

      {:ok, attrs}
    end
  end
end
