defmodule Nest.Persistence do
  @moduledoc """
  Wrapper around the DB-touching parts of starting an Agent
  and the agent + message persistence layer.

  Centralises the "load and start" pattern so test code and
  production code call the same function. Tests rely on the
  test process already owning a sandboxed connection (see
  `Nest.DataCase.setup_sandbox/1`); production uses the global
  Ecto pool. Either way, the DB read happens in the calling
  process, which lets the Agent's `init/1` skip DB work and
  inherit `$callers` for subsequent handler DB writes.

  ## Why this exists

  The Agent's `init/1` historically called
  `Vocations.get_vocation/1` itself. That worked in sync tests
  but broke async tests: the Ecto Sandbox's `shared: true` mode
  is repo-wide, so concurrent async tests racing for it got
  `:already_shared`. Moving the load to the calling process
  sidesteps the shared-mode lock entirely — the caller already
  has a connection via the regular pool (or the test's
  sandboxed checkout), and the agent's later `Repo` calls walk
  `$callers` back to that same connection with no per-pid
  `Sandbox.allow/3`.

  ## Agent + message persistence

  `insert_agent/1` writes a new `agents` row (the integer `id`
  is autogenerated; `{space_id, name}` is the unique composite
  key). `fetch_agent/2` and `list_agent_names_for_space/1` are
  the read paths. The Agent's `__append_message__/2` calls
  `insert_message/3` immediately after appending to in-memory
  state; on `__compaction_completed__/2` it calls
  `record_compaction/6`. `load_messages/2` returns the full
  ordered sequence for the on-demand-load path in
  `Supervisor.fetch_or_start_agent/2`; the caller partitions
  into active/history using `agents.last_compaction_index`
  (read via `last_compaction_index/2` or returned with
  `build_attrs_for_start/2`'s preloaded attrs).

  Externally, callers pass `{space_id, name}`. Internally,
  `messages.agent_id` is the bigserial `agents.id` (an
  integer); this module handles the resolution.

  ## Why retried inserts

  `insert_agent/1` returns `{:error, :duplicate_name}` on a
  Postgres `23505` unique violation. The supervisor catches
  that result, regenerates a fresh name, and retries; the
  unique-index constraint on `(agents.space_id, agents.name)`
  is the ultimate arbiter of uniqueness across BEAMs.
  """

  import Ecto.Query, warn: false
  require Logger

  alias Ecto.Changeset
  alias Nest.Agents.Agent.Restore
  alias Nest.Agents.PersistedAgent
  alias Nest.Agents.PersistedMessage
  alias Nest.Messages.Compaction
  alias Nest.Messages.Message
  alias Nest.Persistence.CompactionMarker
  alias Nest.Repo
  alias Nest.Vocations

  @doc """
  Resolve a `vocation_id` to a loaded `Vocations.Vocation`
  struct (or `nil` if the id is `nil`).

  Returns `nil` (not raising) when the id is non-nil but no
  record exists; matches `Vocations.get_vocation/1`.
  """
  @spec load_vocation(integer() | nil) :: Vocations.Vocation.t() | nil
  def load_vocation(nil), do: nil
  def load_vocation(vocation_id), do: Vocations.get_vocation(vocation_id)

  @doc """
  Build the attrs map the Agent expects, with `:vocation`
  pre-loaded from the DB.

  Pass any other Agent attrs in `attrs` (`space_id`, `name`,
  `model`, `workspace_path`, etc.) — they're merged on top of
  the loaded vocation. `:vocation_id` may be passed by callers
  who don't have the struct handy; this function does the
  fetch and returns the merged map.
  """
  @spec build_agent_attrs(map()) :: map()
  def build_agent_attrs(attrs) do
    attrs
    |> maybe_load_vocation()
  end

  defp maybe_load_vocation(%{vocation: _vocation} = attrs), do: attrs

  defp maybe_load_vocation(%{vocation_id: id} = attrs) when not is_nil(id) do
    Map.put(attrs, :vocation, load_vocation(id))
  end

  defp maybe_load_vocation(attrs), do: attrs

  @doc """
  Insert a new agent row. The integer `id` is autogenerated
  by the DB; `{space_id, name}` is the unique composite key.
  `attrs` carries `:space_id`, `:name`, `:model`,
  `:vocation_id`, `:workspace_path`. `:next_message_index`
  defaults to 0 and the runtime bumps it via
  `update_next_message_index/3` when messages are appended.

  Returns `{:ok, %PersistedAgent{}}` on success,
  `{:error, :duplicate_name}` when the `(space_id, name)`
  unique index rejects the insert (Postgres `23505`),
  `{:error, :missing_required_field}` when a required
  attribute (`:space_id`, `:name`, `:model`) is absent, or
  `{:error, %Ecto.Changeset{}}` on validation failure.
  """
  @spec insert_agent(map()) ::
          {:ok, PersistedAgent.t()}
          | {:error, :duplicate_name | :missing_required_field | Changeset.t(PersistedAgent.t())}
  def insert_agent(attrs) do
    now = now()

    case build_insert_base(attrs, now) do
      {:error, _} = err ->
        err

      base ->
        do_insert(base)
    end
  end

  defp build_insert_base(attrs, now) do
    name = Map.get(attrs, :name)
    space_id = Map.get(attrs, :space_id)
    model = Map.get(attrs, :model)

    if is_binary(name) and is_integer(space_id) and not is_nil(model) do
      %{
        name: name,
        space_id: space_id,
        model: model,
        vocation_id: Map.get(attrs, :vocation_id),
        workspace_path: Map.get(attrs, :workspace_path),
        next_message_index: Map.get(attrs, :next_message_index, 0),
        parent_id: Map.get(attrs, :parent_id),
        depth: Map.get(attrs, :depth, 0),
        created_by_user_id: Map.get(attrs, :created_by_user_id),
        shared: Map.get(attrs, :shared, false),
        inserted_at: now,
        updated_at: now
      }
    else
      {:error, :missing_required_field}
    end
  end

  # Translate a Postgres `23505` unique violation on the
  # `(space_id, name)` composite key into the supervisor-
  # friendly `:duplicate_name` sentinel.
  defp do_insert(base) do
    case Repo.insert(%PersistedAgent{} |> PersistedAgent.changeset(base)) do
      {:ok, row} ->
        {:ok, row}

      {:error, %Changeset{errors: errors} = changeset} ->
        if duplicate_name?(errors) do
          {:error, :duplicate_name}
        else
          {:error, changeset}
        end
    end
  end

  defp duplicate_name?([{_field, {_, details}} | _]) when is_list(details) do
    Keyword.get(details, :constraint) == :unique
  end

  defp duplicate_name?([_ | rest]), do: duplicate_name?(rest)
  defp duplicate_name?([]), do: false

  @doc """
  Fetch the agent row by `{space_id, name}`.
  Returns `{:ok, %PersistedAgent{}}` when found, otherwise
  `{:error, :not_found}`. Used by the supervisor's restore
  path and by all message-write helpers that resolve the
  FK from a name.
  """
  @spec fetch_agent(integer(), String.t()) ::
          {:ok, PersistedAgent.t()} | {:error, :not_found}
  def fetch_agent(space_id, name) do
    case from(a in PersistedAgent, where: a.space_id == ^space_id and a.name == ^name)
         |> Repo.one() do
      nil -> {:error, :not_found}
      %PersistedAgent{} = row -> {:ok, row}
    end
  end

  @doc """
  Delete the agent row for `{space_id, name}`. Returns `:ok`
  whether or not the row existed.

  `Nest.Agents.delete_agent/2` only terminates the BEAM
  process. Callers that want to also remove the DB row call
  this after the process exits.
  """
  @spec delete_agent(integer(), String.t()) :: :ok
  def delete_agent(space_id, name) do
    {_count, _} =
      Repo.delete_all(
        from(a in PersistedAgent, where: a.space_id == ^space_id and a.name == ^name)
      )

    :ok
  end

  @doc """
  List every agent name in a space. Used by the
  `Supervisor`'s name generator to pre-load existing
  names into the in-process uniqueness `MapSet`, reducing
  the probability of a Postgres unique-constraint collision.
  """
  @spec list_agent_names_for_space(integer()) :: [String.t()]
  def list_agent_names_for_space(space_id) do
    from(a in PersistedAgent, where: a.space_id == ^space_id, select: a.name)
    |> Repo.all()
  end

  @doc """
  Persist a runtime message into the `messages` table.

  `space_id` and `agent_name` identify the agent.
  `message` is the canonical `Message.t()` tagged tuple.
  The agent's integer FK (`agents.id`) is resolved
  internally.

  Returns `{:ok, %PersistedMessage{}}` on success, or
  `{:error, term()}` on failure.
  """
  @spec insert_message(integer(), String.t(), Message.t()) ::
          {:ok, PersistedMessage.t()} | {:error, term()}
  def insert_message(space_id, agent_name, message) do
    case fetch_agent(space_id, agent_name) do
      {:error, :not_found} ->
        {:error, :agent_not_found}

      {:ok, %PersistedAgent{id: agent_id}} ->
        insert_message_with_agent_id(agent_id, agent_name, message)
    end
  end

  defp insert_message_with_agent_id(agent_id, agent_name, {:compaction, _} = message) do
    case message do
      {:compaction, %Compaction{} = marker} ->
        CompactionMarker.record(
          agent_id,
          marker.index,
          marker.archived_count,
          marker.tokens_compacted,
          marker.tokens_compacted_to
        )

      other ->
        Logger.warning(
          "Compaction tuple without %Compaction{} struct: #{inspect(other)}. " <>
            "agent=#{agent_name}"
        )
    end
  end

  defp insert_message_with_agent_id(agent_id, _agent_name, message) do
    attrs = PersistedMessage.from_runtime(agent_id, message)

    %PersistedMessage{}
    |> PersistedMessage.changeset(attrs)
    |> Repo.insert(
      on_conflict: :nothing,
      conflict_target: [:agent_id, :message_index]
    )
  end

  @doc """
  Insert a `role: "compaction"` marker row at `marker_index`
  and bump `agents.last_compaction_index` to match.

  Returns the new marker row on success,
  `{:error, :agent_not_found}` when the agent does not
  resolve, or `{:error, term()}` on other failures.
  """
  @spec record_compaction(
          integer(),
          String.t(),
          non_neg_integer(),
          non_neg_integer(),
          non_neg_integer() | nil,
          non_neg_integer() | nil
        ) :: {:ok, PersistedMessage.t()} | {:error, term()}
  def record_compaction(
        space_id,
        agent_name,
        marker_index,
        archived_count,
        tokens_compacted \\ nil,
        tokens_compacted_to \\ nil
      ) do
    case fetch_agent(space_id, agent_name) do
      {:error, :not_found} ->
        {:error, :agent_not_found}

      {:ok, %PersistedAgent{id: agent_id}} ->
        CompactionMarker.record(
          agent_id,
          marker_index,
          archived_count,
          tokens_compacted,
          tokens_compacted_to
        )
    end
  end

  @doc """
  Bump the `next_message_index` column on the agent row.
  """
  defdelegate update_next_message_index(space_id, name, new_index),
    to: Nest.Persistence.Messages,
    as: :update_next_message_index

  @doc """
  Load every message for an agent.
  """
  defdelegate load_messages(space_id, name),
    to: Nest.Persistence.Messages,
    as: :load_messages

  @doc """
  Read the `last_compaction_index` boundary column.
  """
  defdelegate last_compaction_index(space_id, name),
    to: Nest.Persistence.Messages,
    as: :last_compaction_index

  @doc """
  Convenience: load the agent row, the full message sequence,
  the boundary pointer, and the vocation struct. Returns
  `{:ok, attrs_map}` for `Agent.start_link/1`, or
  `{:error, :not_found}` when no row exists for the name.
  """
  @spec build_attrs_for_start(integer(), String.t()) ::
          {:ok, map()} | {:error, :not_found}
  def build_attrs_for_start(space_id, agent_name) do
    with {:ok, row} <- fetch_agent(space_id, agent_name),
         {:ok, boundary} <- last_compaction_index(space_id, agent_name) do
      preloaded = load_messages(space_id, agent_name)
      parent_name = parent_name_for(row)

      attrs = %{
        space_id: row.space_id,
        name: row.name,
        model: row.model,
        vocation_id: row.vocation_id,
        workspace_path: row.workspace_path,
        next_message_index: row.next_message_index,
        last_compaction_index: boundary,
        parent_id: row.parent_id,
        parent_name: parent_name,
        depth: row.depth || 0,
        created_by_user_id: row.created_by_user_id,
        shared: row.shared == true,
        initial_api_log_sequences: Restore.initial_sequences_for(preloaded),
        preloaded_messages: preloaded,
        vocation: load_vocation(row.vocation_id)
      }

      {:ok, attrs}
    end
  end

  # Look up the parent agent's name by integer FK. Children
  # share the parent's `space_id` (see
  # `Supervisor.start_agent_with_parent/2`), so a single
  # query resolves the link without rescanning the full
  # table. Returns `nil` when this agent is a root (no
  # `parent_id`) or when the parent row has been deleted
  # out from under the child — the latter case leaves the
  # child without a parent to notify, matching the
  # pre-restart `nil` behaviour.
  defp parent_name_for(%PersistedAgent{parent_id: nil}), do: nil

  defp parent_name_for(%PersistedAgent{parent_id: parent_id, space_id: space_id}) do
    from(a in PersistedAgent,
      where: a.id == ^parent_id and a.space_id == ^space_id,
      select: a.name
    )
    |> Repo.one()
  end

  @doc """
  Update the `model` column on an agent row.
  """
  defdelegate update_agent_model(space_id, name, model_map),
    to: Nest.Persistence.AgentAttrs,
    as: :update_agent_model

  @doc """
  List every persisted agent row in `space_id`, ordered by name.
  """
  defdelegate fetch_all_agents_for_space(space_id),
    to: Nest.Persistence.AgentAttrs,
    as: :fetch_all_agents_for_space

  @doc """
  Mark the agent row for `{space_id, name}` as archived.
  """
  defdelegate archive_agent(space_id, name),
    to: Nest.Persistence.AgentAttrs,
    as: :archive_agent

  @doc """
  Current UTC timestamp truncated to second precision.
  """
  @spec now() :: DateTime.t()
  def now, do: DateTime.utc_now() |> DateTime.truncate(:second)
end
