defmodule Nest.PersistenceTest do
  @moduledoc """
  Tests for the `Nest.Persistence` agent + message persistence
  layer.

  Covers:
  - `insert_agent/1` insert + `:duplicate_name` path
  - `fetch_agent_by_name/1` round-trip
  - `list_agent_names/0`
  - `insert_message/2` for each role (system, user, assistant, tool,
    compaction)
  - `archive_and_compact/4` transaction (archive + marker insert)
  - `load_active_messages/1` round-trip (preserves parts and
    message_index)
  - `build_attrs_for_start/1` returns attrs that flow into
    `Agent.start_link`

  Persistence is enabled in this test process via the `:nest,
  :persistence` app env (test-only override), so the `Agent`
  GenServer — which normally has persistence disabled via the
  runtime check — can write through to the DB and the
  `:append_message` smoke test exercises the live path.
  """

  use Nest.DataCase, async: false

  import ExUnit.Callbacks

  alias Nest.Agents.PersistedAgent
  alias Nest.Agents.PersistedMessage
  alias Nest.Messages.Assistant
  alias Nest.Messages.Part
  alias Nest.Messages.System, as: MsgSystem
  alias Nest.Messages.Tool
  alias Nest.Messages.User
  alias Nest.Persistence

  setup do
    # The `Agent` GenServer reads `persistence_enabled?/0` from
    # this process's app env at request time. The runtime
    # default (`false` in test) would skip writes even when the
    # Sandbox has a connection; toggle it back on for this test
    # process so we exercise the real DB write paths.
    Application.put_env(:nest, :persistence, enabled: true)

    on_exit(fn ->
      Application.put_env(:nest, :persistence, enabled: false)
    end)

    :ok
  end

  describe "insert_agent/1" do
    test "inserts a new agent row and returns the autogenerated id" do
      attrs = agent_attrs("insert-new-#{Elixir.System.unique_integer([:positive])}")

      assert {:ok, %PersistedAgent{id: id, name: name}} = Persistence.insert_agent(attrs)
      assert is_integer(id) and id > 0
      assert name == attrs.name
    end

    test "returns :duplicate_name when the name already exists" do
      attrs = agent_attrs("dup-name-#{Elixir.System.unique_integer([:positive])}")

      assert {:ok, _row} = Persistence.insert_agent(attrs)
      assert {:error, :duplicate_name} = Persistence.insert_agent(attrs)
    end

    test "validates required fields" do
      assert {:error, %Ecto.Changeset{} = changeset} =
               Persistence.insert_agent(%{name: "", model: %{}})

      refute Enum.empty?(changeset.errors)
    end

    test "returns :missing_required_field when :model is absent" do
      # Defensive guard so a future caller (or the same regression)
      # cannot crash the supervisor with a KeyError; returns the
      # sentinel that lets `do_fetch_or_start_with_persistence/1`
      # match on `:not_found`-like cases without raising.
      assert {:error, :missing_required_field} =
               Persistence.insert_agent(%{name: "no-model-agent"})

      assert {:error, :missing_required_field} =
               Persistence.insert_agent(%{})
    end
  end

  describe "fetch_agent_by_name/1" do
    test "finds the row by name" do
      attrs = agent_attrs("fetch-#{Elixir.System.unique_integer([:positive])}")
      assert {:ok, inserted} = Persistence.insert_agent(attrs)

      assert {:ok, %PersistedAgent{name: name, id: id}} =
               Persistence.fetch_agent_by_name(attrs.name)

      assert id == inserted.id
      assert name == attrs.name
    end

    test "returns :not_found for an unknown name" do
      assert {:error, :not_found} =
               Persistence.fetch_agent_by_name("never-seen")
    end
  end

  describe "list_agent_names/0" do
    test "returns one entry per persisted agent" do
      suffix = Elixir.System.unique_integer([:positive])
      a = agent_attrs("list-a-#{suffix}")
      b = agent_attrs("list-b-#{suffix}")
      {:ok, _} = Persistence.insert_agent(a)
      {:ok, _} = Persistence.insert_agent(b)

      names = Persistence.list_agent_names()
      assert a.name in names
      assert b.name in names
    end
  end

  describe "insert_message/2" do
    test "round-trips a system message" do
      attrs = agent_attrs("msg-system-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      message = {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "You are helpful"}]}}

      assert {:ok, %PersistedMessage{} = row} = Persistence.insert_message(attrs.name, message)
      assert row.role == "system"
      assert row.message_index == 0
      assert row.content == %{"parts" => [%{"kind" => "text", "text" => "You are helpful"}]}
    end

    test "round-trips a user message with mode metadata" do
      attrs = agent_attrs("msg-user-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      message =
        {:user,
         %User{
           index: 1,
           parts: [%Part.Text{text: "[mode: chat]\nHello"}],
           metadata: %{"mode" => "chat"}
         }}

      assert {:ok, %PersistedMessage{} = row} = Persistence.insert_message(attrs.name, message)
      assert row.role == "user"
      assert row.message_index == 1
      assert row.metadata == %{"mode" => "chat"}
    end

    test "round-trips an assistant message with multiple parts (text + thinking + tool_use)" do
      attrs = agent_attrs("msg-assistant-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      message =
        {:assistant,
         %Assistant{
           index: 2,
           parts: [
             %Part.Text{text: "I'll call a tool"},
             %Part.Thinking{thinking: "let me think", signature: "sig-abc"},
             %Part.ToolUse{
               id: "call_1",
               name: "shell_cmd",
               arguments: %{"command" => "ls"}
             }
           ],
           usage: %{
             "input_tokens" => 100,
             "output_tokens" => 20,
             "total_tokens" => 120
           },
           finish_reason: "tool_calls",
           model: "claude-3-opus"
         }}

      assert {:ok, %PersistedMessage{} = row} = Persistence.insert_message(attrs.name, message)

      assert row.role == "assistant"
      assert row.message_index == 2

      assert %{"parts" => parts, "usage" => usage, "finishReason" => "tool_calls"} =
               row.content

      assert usage == %{
               "input_tokens" => 100,
               "output_tokens" => 20,
               "total_tokens" => 120
             }

      assert [%{"kind" => "text", "text" => "I'll call a tool"}, _thinking, tool_use] = parts
      assert tool_use["kind"] == "tool_use"
      assert tool_use["name"] == "shell_cmd"
    end

    test "round-trips a tool message with multiple tool results" do
      attrs = agent_attrs("msg-tool-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      message =
        {:tool,
         %Tool{
           index: 3,
           parts: [
             %Part.ToolResult{
               tool_call_id: "call_1",
               name: "shell_cmd",
               content: "ok",
               is_error: false
             },
             %Part.ToolResult{
               tool_call_id: "call_2",
               name: "read_file",
               content: "boom",
               is_error: true
             }
           ]
         }}

      assert {:ok, %PersistedMessage{} = row} = Persistence.insert_message(attrs.name, message)
      assert row.role == "tool"

      assert %{"parts" => [r1, r2]} = row.content
      assert r1["kind"] == "tool_result"
      assert r1["toolCallId"] == "call_1"
      assert r2["isError"] == true
    end

    test "returns :agent_not_found for an unknown name" do
      message = {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "hi"}]}}

      assert {:error, :agent_not_found} =
               Persistence.insert_message(
                 "never-seen-#{Elixir.System.unique_integer([:positive])}",
                 message
               )
    end
  end

  describe "load_active_messages/1" do
    test "returns active (non-archived) messages in message_index order" do
      attrs = agent_attrs("load-active-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "sys"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 1, parts: [%Part.Text{text: "hi"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:assistant, %Assistant{index: 2, parts: [%Part.Text{text: "hello"}]}}
        )

      messages = Persistence.load_active_messages(attrs.name)
      assert length(messages) == 3
      assert Enum.map(messages, fn {_, %{index: idx}} -> idx end) == [0, 1, 2]
    end

    test "round-trip preserves parts (text + thinking + tool_use)" do
      attrs = agent_attrs("load-roundtrip-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      original_parts = [
        %Part.Text{text: "visible"},
        %Part.Thinking{thinking: "hidden", signature: "sig-xyz"},
        %Part.ToolUse{id: "call_1", name: "shell_cmd", arguments: %{"cmd" => "ls"}}
      ]

      original =
        {:assistant,
         %Assistant{
           index: 0,
           parts: original_parts,
           usage: %{"input_tokens" => 10},
           finish_reason: "tool_calls"
         }}

      assert {:ok, _} = Persistence.insert_message(attrs.name, original)

      [{:assistant, restored}] = Persistence.load_active_messages(attrs.name)
      assert restored.parts == original_parts
      assert restored.usage == %{"input_tokens" => 10}
      assert restored.finish_reason == "tool_calls"
    end

    test "empty agent returns empty list" do
      assert Persistence.load_active_messages(
               "load-empty-#{Elixir.System.unique_integer([:positive])}"
             ) == []
    end
  end

  describe "archive_and_compact/4" do
    test "archives a range of messages and inserts a compaction marker" do
      attrs = agent_attrs("archive-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 0, parts: [%Part.Text{text: "First"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:assistant, %Assistant{index: 1, parts: [%Part.Text{text: "Reply"}]}}
        )

      # Archive indices 0..1 (both messages) and insert a
      # marker at index 2.
      assert {:ok, %PersistedMessage{} = marker} =
               Persistence.archive_and_compact(attrs.name, 0, 1, 2)

      assert marker.role == "compaction"
      assert marker.message_index == 2
      assert marker.compaction_archived_count == 2
      assert marker.compaction_occurred_at != nil

      active = Persistence.load_active_messages(attrs.name)
      assert length(active) == 1

      [{:compaction, m}] = active
      assert m.archived_count == 2

      from_db = Nest.Repo.all(PersistedMessage)
      assert length(from_db) == 3
      assert Enum.all?(Enum.drop(from_db, -1), &(&1.archived_at != nil))
    end
  end

  describe "update_next_message_index/2" do
    test "bumps the agent's counter" do
      attrs = agent_attrs("counter-#{Elixir.System.unique_integer([:positive])}")
      {:ok, %PersistedAgent{id: agent_id}} = Persistence.insert_agent(attrs)

      :ok = Persistence.update_next_message_index(attrs.name, 5)

      assert [%PersistedAgent{id: ^agent_id, next_message_index: 5}] =
               Nest.Repo.all(PersistedAgent)
    end

    test "returns :agent_not_found for an unknown name" do
      assert {:error, :agent_not_found} =
               Persistence.update_next_message_index(
                 "counter-missing-#{Elixir.System.unique_integer([:positive])}",
                 1
               )
    end
  end

  describe "build_attrs_for_start/1" do
    test "returns attrs suitable for Agent.start_link" do
      attrs = agent_attrs("restore-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "sys"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 1, parts: [%Part.Text{text: "hi"}]}}
        )

      {:ok, restored} = Persistence.build_attrs_for_start(attrs.name)

      assert restored.name == attrs.name

      assert restored.model["name"] == attrs.model.name
      assert restored.model["provider"] == attrs.model.provider
      assert restored.workspace_path == attrs.workspace_path
      assert length(restored.preloaded_messages) == 2
    end

    test "returns :not_found when no row exists" do
      assert {:error, :not_found} =
               Persistence.build_attrs_for_start(
                 "nonexistent-#{Elixir.System.unique_integer([:positive])}"
               )
    end
  end

  ## Helpers

  defp agent_attrs(name) do
    %{
      name: name,
      model: %{name: "test-model", provider: "test"},
      workspace_path: nil
    }
  end
end
