defmodule Nest.PersistenceAgentsTest do
  @moduledoc """
  Tests for `Nest.Persistence`'s agent CRUD surface and
  `build_attrs_for_start/1`. Lives in a separate file from
  `Nest.PersistenceTest` (which covers messages + compaction)
  to keep each file under credo's 500-line limit.

  Covers:
  - `insert_agent/1` insert + `:duplicate_name` path + validation
  - `fetch_agent_by_name/1` round-trip + `:not_found`
  - `list_agent_names/0`
  - `build_attrs_for_start/1` returns attrs that flow into
    `Agent.start_link`, including `:last_compaction_index`

  Persistence is enabled for this test process via the
  `:nest, :persistence` app env.
  """

  use Nest.DataCase, async: true

  import Nest.PersistenceTestHelpers

  alias Nest.Agents.PersistedAgent
  alias Nest.Messages.Assistant
  alias Nest.Messages.Part
  alias Nest.Messages.System, as: MsgSystem
  alias Nest.Messages.User
  alias Nest.Persistence

  describe "insert_agent/1" do
    test "inserts a new agent row and returns the autogenerated id" do
      attrs = agent_attrs("insert-new-#{Elixir.System.unique_integer([:positive])}")

      assert {:ok, %PersistedAgent{id: id, name: name}} = Persistence.insert_agent(attrs)
      assert is_integer(id) and id > 0
      assert name == attrs.name

      # last_compaction_index defaults to -1 on insert.
      assert Nest.Repo.one!(PersistedAgent, where: [name: name]).last_compaction_index == -1
    end

    test "returns :duplicate_name when the name already exists" do
      attrs = agent_attrs("dup-name-#{Elixir.System.unique_integer([:positive])}")

      assert {:ok, _row} = Persistence.insert_agent(attrs)
      assert {:error, :duplicate_name} = Persistence.insert_agent(attrs)
    end

    test "validates required fields" do
      assert {:error, %Ecto.Changeset{} = changeset} =
               Persistence.insert_agent(%{name: "", model: %{}})

      refute Enum.empty?(changeset.errors)
    end

    test "returns :missing_required_field when :model is absent" do
      assert {:error, :missing_required_field} =
               Persistence.insert_agent(%{name: "no-model-agent"})

      assert {:error, :missing_required_field} =
               Persistence.insert_agent(%{})
    end
  end

  describe "fetch_agent_by_name/1" do
    test "finds the row by name" do
      attrs = agent_attrs("fetch-#{Elixir.System.unique_integer([:positive])}")
      assert {:ok, inserted} = Persistence.insert_agent(attrs)

      assert {:ok, %PersistedAgent{name: name, id: id}} =
               Persistence.fetch_agent_by_name(attrs.name)

      assert id == inserted.id
      assert name == attrs.name
    end

    test "returns :not_found for an unknown name" do
      assert {:error, :not_found} =
               Persistence.fetch_agent_by_name("never-seen")
    end
  end

  describe "list_agent_names/0" do
    test "returns one entry per persisted agent" do
      suffix = Elixir.System.unique_integer([:positive])
      a = agent_attrs("list-a-#{suffix}")
      b = agent_attrs("list-b-#{suffix}")
      {:ok, _} = Persistence.insert_agent(a)
      {:ok, _} = Persistence.insert_agent(b)

      names = Persistence.list_agent_names()
      assert a.name in names
      assert b.name in names
    end
  end

  describe "build_attrs_for_start/1" do
    test "returns attrs suitable for Agent.start_link including last_compaction_index" do
      attrs = agent_attrs("restore-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "sys"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 1, parts: [%Part.Text{text: "hi"}]}}
        )

      assert {:ok, _} = Persistence.record_compaction(attrs.name, 2, 2)

      {:ok, restored} = Persistence.build_attrs_for_start(attrs.name)

      assert restored.name == attrs.name
      # `build_attrs_for_start/1` round-trips the JSONB `model`
      # column (string keys), while `attrs.model` was the test's
      # atom-keyed input. Use the shape-flexible idiom so the
      # test stays valid regardless of which keying the function
      # returns in the future.
      assert (restored.model[:name] || restored.model["name"]) == attrs.model.name
      assert (restored.model[:provider] || restored.model["provider"]) == attrs.model.provider
      assert restored.workspace_path == attrs.workspace_path
      assert restored.last_compaction_index == 2

      # 3 preloaded messages: system@0, user@1, marker@2.
      # Partition happens inside Agent.init/1's seed_from_db/3.
      assert length(restored.preloaded_messages) == 3
    end

    test "returns :not_found when no row exists" do
      assert {:error, :not_found} =
               Persistence.build_attrs_for_start(
                 "nonexistent-#{Elixir.System.unique_integer([:positive])}"
               )
    end

    test "includes :initial_api_log_sequences for user/tool preloaded messages" do
      attrs = agent_attrs("seq-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:system, %MsgSystem{index: 0, parts: [%Part.Text{text: "sys"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 1, parts: [%Part.Text{text: "hi"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:user, %User{index: 2, parts: [%Part.Text{text: "again"}]}}
        )

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:assistant, %Assistant{index: 3, parts: [%Part.Text{text: "sure"}]}}
        )

      {:ok, restored} = Persistence.build_attrs_for_start(attrs.name)

      # `:user` indices 1 and 2 get sequence 1; `:assistant` at 3
      # does not (populated via DB row instead).
      assert restored.initial_api_log_sequences == %{1 => 1, 2 => 1}
    end

    test "round-trips assistant api_logs through insert + build_attrs_for_start" do
      attrs = agent_attrs("roundtrip-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      log = %{
        id: "003.000",
        timestamp: DateTime.utc_now(),
        type: :request,
        payload: %{"messages" => [%{"role" => "user", "content" => "hi"}]}
      }

      {:ok, _} =
        Persistence.insert_message(
          attrs.name,
          {:assistant,
           %Assistant{
             index: 1,
             parts: [%Part.Text{text: "hello"}],
             api_logs: [log]
           }}
        )

      {:ok, restored} = Persistence.build_attrs_for_start(attrs.name)

      # Find the assistant message in the preloaded list.
      {:assistant, %Assistant{api_logs: api_logs}} =
        Enum.find(restored.preloaded_messages, &match?({:assistant, _}, &1))

      # api_logs survive the round-trip with their atom keys (the
      # runtime path reads `log.type == :request` directly).
      assert length(api_logs) == 1
      assert hd(api_logs).id == "003.000"
      assert hd(api_logs).type == :request
    end
  end

  describe "update_agent_model/2" do
    test "replaces the jsonb model column with the new map" do
      attrs = agent_attrs("update-model-#{Elixir.System.unique_integer([:positive])}")
      {:ok, _} = Persistence.insert_agent(attrs)

      new_model = %{"name" => "claude-3-opus-20240229", "provider" => "anthropic-provider"}

      assert :ok = Persistence.update_agent_model(attrs.name, new_model)

      {:ok, %PersistedAgent{model: persisted_model}} =
        Persistence.fetch_agent_by_name(attrs.name)

      # jsonb columns come back with string keys.
      assert persisted_model == new_model
    end

    test "returns :not_found when the agent row is absent" do
      new_model = %{"name" => "ghost", "provider" => "ghost"}
      assert {:error, :not_found} = Persistence.update_agent_model("missing-agent", new_model)
    end

    test "touches updated_at on the existing row" do
      attrs = agent_attrs("update-model-ts-#{Elixir.System.unique_integer([:positive])}")
      {:ok, %PersistedAgent{updated_at: original_ts}} = Persistence.insert_agent(attrs)

      new_model = %{"name" => "qwen3.5-plus", "provider" => "model-studio"}
      :ok = Persistence.update_agent_model(attrs.name, new_model)

      {:ok, %PersistedAgent{updated_at: new_ts}} =
        Persistence.fetch_agent_by_name(attrs.name)

      # Both timestamps may equal each other within the second
      # truncation window. Compare using `>=` so a fast-clock
      # tick between the two writes counts.
      assert DateTime.compare(new_ts, original_ts) in [:gt, :eq]
    end
  end

  describe "fetch_all_agents/0" do
    test "lists every persisted agent, ordered by name" do
      base = "list-#{Elixir.System.unique_integer([:positive])}"
      attrs_a = agent_attrs("#{base}-a")
      attrs_b = agent_attrs("#{base}-b")
      attrs_c = agent_attrs("#{base}-c")

      {:ok, _} = Persistence.insert_agent(attrs_a)
      {:ok, _} = Persistence.insert_agent(attrs_b)
      {:ok, _} = Persistence.insert_agent(attrs_c)

      all = Persistence.fetch_all_agents() |> Enum.map(& &1.name)
      assert "#{base}-a" in all
      assert "#{base}-b" in all
      assert "#{base}-c" in all
    end
  end
end
