defmodule Nest.Agents.SupervisorTest do
  @moduledoc """
  Tests for the unified `Supervisor.fetch_or_start_agent/1`
  entry point and the supporting `start_agent/1`,
  `stop_agent/1`, `list_agents/0`, and `get_agent/1`
  functions.

  The new flow:

    * `fetch_or_start_agent/1` — single function for both
      "start new" and "lazy-restore" paths. The DB is the
      source of truth for "does this name exist?".
    * `insert_agent/1` returns `{:error, :duplicate_name}` on
      a Postgres `23505` unique violation; the supervisor
      catches that result and retries with a regenerated
      name (up to 5 attempts).

  Persistence is disabled in this test module (the
  default test env). The `fetch_or_start_agent/1` path
  exercised here is the in-process `Registry` fallback
  (`do_fetch_or_start_no_persistence`).
  """
  use ExUnit.Case, async: true

  import Eventually

  alias Nest.Agents.{Registry, Supervisor}

  setup do
    # Note: we deliberately do NOT call `Supervisor.stop_agent/1`
    # on every existing agent here. With `async: true`, that would
    # kill agents created by other concurrent tests (e.g. the
    # channel tests' per-test agents), which then fail with
    # "agent not found" at subscribe_and_join. Per-test cleanup
    # belongs in the test that owns the agent, not in a shared
    # setup block.
    #
    # We also don't wipe /tmp/nest-VMPID/ because the path is
    # shared across all tests in this BEAM VM and wiping in setup
    # races with concurrent async tests' agents. Per-agent cleanup
    # is the agent's own responsibility in `terminate/2`.

    :ok
  end

  describe "fetch_or_start_agent/1" do
    test "starts an agent with an autogenerated name" do
      {:ok, name} = Supervisor.fetch_or_start_agent(%{model: %{name: "qwen3.5-plus"}})
      assert Regex.match?(~r/^[a-z]+-[a-z]+$/, name)
      assert {:ok, _pid} = Registry.lookup(name)
    end

    test "starts an agent with an explicit name" do
      {:ok, "custom-name"} =
        Supervisor.fetch_or_start_agent(%{
          name: "custom-name",
          model: %{name: "qwen3.5-plus"}
        })

      assert {:ok, _pid} = Registry.lookup("custom-name")
    end
  end

  describe "stop_agent/1" do
    test "stops agent and removes from registry" do
      {:ok, name} = Supervisor.fetch_or_start_agent(%{model: %{name: "qwen3.5-plus"}})
      assert {:ok, pid} = Registry.lookup(name)
      assert Process.alive?(pid)

      :ok = Supervisor.stop_agent(name)

      # The registry's auto-cleanup happens asynchronously after the
      # process exits, so poll until the lookup reflects the removal.
      assert eventually(fn -> Registry.lookup(name) == {:error, :not_found} end,
               timeout: 1000
             )
    end

    test "returns error for non-existent agent" do
      assert {:error, :not_found} = Supervisor.stop_agent("nonexistent")
    end
  end

  describe "list_agents/0" do
    test "returns list of running agent names" do
      {:ok, name1} = Supervisor.fetch_or_start_agent(%{model: %{name: "qwen3.5-plus"}})
      {:ok, name2} = Supervisor.fetch_or_start_agent(%{model: %{name: "MiniMax-M2.5"}})

      # In async mode, other tests may have started/stopped agents
      # concurrently. Assert on this test's own names (definitely
      # present) and an inclusive lower bound on the total — not
      # an exact count.
      agents = Supervisor.list_agents()
      assert name1 in agents
      assert name2 in agents
      assert length(agents) >= 2
    end

    # The "returns empty list when no agents" test is not expressible
    # in async mode (other tests' agents leak in). It would belong
    # in a separate `async: false` describe block or a dedicated
    # module. Tracked as future work.
  end

  describe "get_agent/1" do
    test "returns agent PID by name" do
      {:ok, name} = Supervisor.fetch_or_start_agent(%{model: %{name: "qwen3.5-plus"}})

      assert {:ok, pid} = Supervisor.get_agent(name)
      assert is_pid(pid)
      assert Process.alive?(pid)
    end

    test "returns error for non-existent name in persistence-disabled mode" do
      # In test mode without persistence, `fetch_or_start_agent/1`
      # answers `:not_found` for any name not in the in-process
      # Registry; the lazy-restore path then forwards that.
      assert {:error, :not_found} =
               Supervisor.get_agent("nonexistent-#{System.unique_integer([:positive])}")
    end
  end

  # Persistence-enabled regression coverage lives in
  # `test/nest/agents/supervisor_persistence_test.exs` — that
  # test module owns a `DataCase` sandbox and toggles the
  # `:persistence` app env on, which is not possible in
  # this `async: true` module.
end
