defmodule Nest.Agents.SupervisorTest do
  @moduledoc """
  Tests for the unified `Supervisor.fetch_or_start_agent/1`
  entry point and the supporting `start_agent/1`,
  `stop_agent/1`, `list_agents/0`, and `get_agent/1`
  functions.

  The new flow:

    * `fetch_or_start_agent/1` — single function for both
      "start new" and "on-demand-load" paths. The DB is the
      source of truth for "does this name exist?".
    * `Agents.create_agent/2` — standard caller interface
      that runs `Agent.pre_spawn/1` (DB row + system
      message) in the caller's pid, then calls
      `Supervisor.fetch_or_start_agent/1` to spawn the
      GenServer under the supervisor.

  Persistence is **enabled** in the test env (see
  `config/test.exs`). All tests in this module are
  `async: true` and run against a `DataCase` sandbox.
  """
  use Nest.DataCase, async: true

  import Eventually

  alias Nest.Agents
  alias Nest.Agents.{Registry, Supervisor}
  alias Nest.Agents.AgentTestHelpers

  setup do
    # Note: we deliberately do NOT call `Supervisor.stop_agent/1`
    # on every existing agent here. With `async: true`, that would
    # kill agents created by other concurrent tests (e.g. the
    # channel tests' per-test agents), which then fail with
    # "agent not found" at subscribe_and_join. Per-test cleanup
    # belongs in the test that owns the agent, not in a shared
    # setup block.
    #
    # We also don't wipe /tmp/nest-VMPID/ because the path is
    # shared across all tests in this BEAM VM and wiping in setup
    # races with concurrent async tests' agents. Per-agent cleanup
    # is the agent's own responsibility in `terminate/2`.

    # No `await_models_refresh/0` needed: this file's tests
    # either use `qwen3.5-plus` (a static-config entry, returned
    # immediately by `Models.list/0` from `state.static_config.models`)
    # or pass `%{provider: "model-studio"}` without a `:name` to
    # force the auto-name path (which starts the agent in
    # `:model_missing` by design).

    :ok
  end

  defp fresh_name, do: "agent#{System.unique_integer([:positive])}"

  defp test_model, do: %{name: "qwen3.5-plus", provider: "model-studio"}

  describe "fetch_or_start_agent/1" do
    test "starts an agent with an autogenerated name" do
      # The supervisor no longer auto-generates names — that
      # responsibility moved to `Agents.create_agent/2`, which
      # calls `Supervisor.generate_unique_name/0` when the
      # caller didn't supply a name (and the model map's
      # `:name` is the LLM identifier, not the agent's
      # registry key). Use a model without a `:name` to
      # force the generator path.
      {{:ok, name}, _log} =
        ExUnit.CaptureLog.with_log(fn ->
          Agents.create_agent(%{provider: "model-studio"},
            vocation_id: AgentTestHelpers.vocation_id_for_test()
          )
        end)

      assert Regex.match?(~r/^[a-z]+-[a-z]+$/, name)
      assert {:ok, _pid} = Registry.lookup(name)
    end

    test "starts an agent with an explicit name" do
      name = fresh_name()

      {:ok, ^name} =
        Agents.create_agent(test_model(),
          name: name,
          vocation_id: AgentTestHelpers.vocation_id_for_test()
        )

      assert {:ok, _pid} = Registry.lookup(name)
    end
  end

  describe "stop_agent/1" do
    test "stops agent and removes from registry" do
      name = fresh_name()

      {:ok, ^name} =
        Agents.create_agent(test_model(),
          name: name,
          vocation_id: AgentTestHelpers.vocation_id_for_test()
        )

      assert {:ok, pid} = Registry.lookup(name)
      assert Process.alive?(pid)

      :ok = Agents.delete_agent(name)

      # The registry's auto-cleanup happens asynchronously after the
      # process exits, so poll until the lookup reflects the removal.
      assert eventually(fn -> Registry.lookup(name) == {:error, :not_found} end,
               timeout: 1000
             )
    end

    test "returns error for non-existent agent" do
      assert {:error, :not_found} = Agents.delete_agent("nonexistent")
    end
  end

  describe "list_agents/0" do
    test "returns list of running agent names" do
      name1 = fresh_name()
      name2 = fresh_name()
      vid = AgentTestHelpers.vocation_id_for_test()

      {:ok, ^name1} = Agents.create_agent(test_model(), name: name1, vocation_id: vid)
      {:ok, ^name2} = Agents.create_agent(test_model(), name: name2, vocation_id: vid)

      # In async mode, other tests may have started/stopped agents
      # concurrently. Assert on this test's own names (definitely
      # present) and an inclusive lower bound on the total — not
      # an exact count.
      agents = Agents.list_agents()
      assert name1 in agents
      assert name2 in agents
      assert length(agents) >= 2
    end

    # The "returns empty list when no agents" test is not expressible
    # in async mode (other tests' agents leak in). It would belong
    # in a separate `async: false` describe block or a dedicated
    # module. Tracked as future work.
  end

  describe "get_agent/1" do
    test "returns agent PID by name" do
      name = fresh_name()

      {:ok, ^name} =
        Agents.create_agent(test_model(),
          name: name,
          vocation_id: AgentTestHelpers.vocation_id_for_test()
        )

      assert {:ok, pid} = Supervisor.get_agent(name)
      assert is_pid(pid)
      assert Process.alive?(pid)
    end

    test "returns error for non-existent name" do
      assert {:error, :not_found} =
               Supervisor.get_agent("nonexistent-#{System.unique_integer([:positive])}")
    end
  end

  # Persistence-enabled regression coverage lives in
  # `test/nest/agents/supervisor_persistence_test.exs` — that
  # test module owns a `DataCase` sandbox and exercises the
  # supervisor's DB-driven flow directly.
end
